name: "prod2.sub1.mod1"
cluster: "prod2.sub1.mod1"
directives:
  - "ip_hash"
routes:
  - domain_groups:
      - name: ghi.example.com
        ports: [10021, 10022, 10031, 10032]
    locations:
      - path: "/users2/"
      - path: "/user-api/v2/"
        directives:
          - "proxy_send_timeout 600s"
        splitting:
          - type: percent
            arguments: [ "$http_x_my_header", "20.00%" ]
            dest_cluster: "prod2.sub1.mod1_gray"
      - path: "/mod2api/v1/"
        directives:
          - "set $my_route_var $http_app_env$cookie_app_env"
        splitting:
          - type: regex
            arguments: [ "$my_route_var", "^gray$" ]
            dest_cluster: "prod2.sub1.mod1_gray"
