name: "prod2.sub2.mod2"
cluster: "prod2.sub2.mod2"
directives:
  - "hash $request_uri consistent"
routes:
  - domain_groups:
      - name: ghi.example.com
        ports: [10033, 10034]
    locations:
      - path: "/ghi2/feeds/"
        directives:
          - "proxy_send_timeout 600"
        splitting:
          - type: percent
            arguments: [ "$http_x_my_header", "20.00%" ]
            dest_cluster: "prod2.sub2.mod2_gray"
      - regex_path: "/users/\\d+/"
        directives:
          - "set $my_route_var $http_app_env$cookie_app_env"
        splitting:
          - type: regex
            arguments: [ "$my_route_var", "^gray$" ]
            dest_cluster: "prod2.sub2.mod2_gray"
          - type: regex
            arguments: [ "$http_app_env", "^gray$" ]
            dest_cluster: "prod2.sub2.mod2_gray"
