name: prod1.sub1.static_upstream_2
cluster: prod1.sub1.static_upstream_2
routes:
  - domain_groups:
      - name: abc.example.com
        ports: [10028, 10029]
    directives: [ ]
    locations:
      - path: "/demo-def/"
        directives:
          - "proxy_connect_timeout 0.5s"
          - "proxy_read_timeout 5s"
