name: prod1.sub1.static_upstream_1
cluster: prod1.sub1.static_upstream_1
routes:
  - domain_groups:
      - name: abc.example.com
        ports: [10028, 10029]
    directives: []
    locations:
      - path: "/demo-abc/"
        directives:
          - "proxy_connect_timeout 0.5s"
          - "proxy_read_timeout 5s"
      - regex_path: "/demo-users/\\d+/"
        directives:
          - "proxy_connect_timeout 0.5s"
          - "proxy_read_timeout 5s"
